<a href="https://colab.research.google.com/github/Dahernandezsilve/HT1MD/blob/main/HT_1_An%C3%A1lisis_Exploratorio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Universidad del Valle de Guatemala
18 Avenida 11-95 Guatemala      
Departamento de Computación     
Facultad de Ingeniería       
Minería de Datos Sección 10         
Fecha de entrega: 29/01/2024        

Grupo 6 | Integrantes:
- Diego Alexander Hernández Silvestre 21270
- Linda Inés Jimenez Vides 21169
- Daniel Armando Valdez Reyes 21240

## HDT8 - RNA
Para realizar una exploración inicial del conjunto de datos, se prodeció a realizar un resumen de la información proporcionada en el dataset del archivo "*train.csv*. A continuación se muestran los resultados: 

*Primero se importan todas la librerías requeridas para llevar a cabo el análisis*

In [30]:
import pandas as pd
from scipy.stats import shapiro, ks_2samp, anderson
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from typing import *
import matplotlib.pyplot as plt
from sklearn import datasets
import sklearn as sklearn
import sklearn.cluster as cluster
import sklearn.metrics as metrics
from sklearn.preprocessing import StandardScaler
import scipy.cluster.hierarchy as sch
import skfuzzy as fuzz
import pylab
import sklearn.mixture as mixture
import pyclustertend 
import random
import statsmodels.api as sm
import statsmodels.stats.diagnostic as smd
from sklearn.linear_model import LinearRegression
from sklearn import datasets
from sklearn.model_selection import train_test_split, cross_val_predict
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.linear_model import Ridge
import seaborn as sns
import statsmodels.api as sm
from statsmodels.graphics.gofplots import qqplot
from yellowbrick.regressor import ResidualsPlot
import scipy.stats as stats
import statsmodels.stats.diagnostic as diag
from scipy.stats import normaltest

from sklearn.svm import SVC
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import root_mean_squared_error
import matplotlib.pyplot as plt
import numpy as np
import random
import statsmodels.api as sm
import statsmodels.stats.diagnostic as smd
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
import seaborn as sns
import statsmodels.api as sm
import scipy.stats as stats
import statsmodels.stats.diagnostic as diag
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

from sklearn.compose import make_column_selector as selector #Para seleccionar de forma automática las variables numéricas y categóricas
from sklearn.preprocessing import OneHotEncoder #Para codificar las variables categóricas usando dummies
from sklearn.preprocessing import StandardScaler #Para normalizar las variables numéricas
from sklearn.compose import ColumnTransformer #Modifica las columnas usando los preprocesadores
from sklearn.pipeline import make_pipeline #Planifica una secuencia de procesos
from sklearn import set_config #Para mostrar graficamente el pipeline
from sklearn.model_selection import GridSearchCV

set_config(display='diagram')
#Metrics
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score ,precision_score,recall_score,f1_score

Se lleva a cabo un análisis identificando los tipos de variables involucradas:
## Descripcion de variables
- MSSubClass: Cuantitativa Discreta
- MSZoning: Cualitativa Categorica	
- LotFrontage: Cuantitativa Medible
- LotArea: Cuantitativa Medible
- Street: Cualitativa Categorica
- Alley: Cualitativa Categorica
- LotShape: Cualitativa Categorica       
- LandContour: Cualitativa Categorica
- Utilities: Cualitativa Categorica		
- LotConfig: Cualitativa Categorica
- LandSlope: Cualitativa Categorica 
- Neighborhood: Cualitativa Categorica
- Condition1: Cualitativa Categorica
- Condition2: Cualitativa Categorica
- BldgType: Cualitativa Categorica
- HouseStyle: Cualitativa Categorica 
- OverallQual: Cuantitativa Discreta
- OverallCond: Cuantitativa Discreta
- YearBuilt: Cuantitativa Discreta
- YearRemodAdd: Cuantitativa Discreta
- RoofStyle: Cualitativa Categorica
- RoofMatl: Cualitativa Categorica
- Exterior1st: Cualitativa Categorica
- Exterior2nd: Cualitativa Categorica
- MasVnrType: Cualitativa Categorica
- MasVnrArea: Cuantitativa Continua
- ExterQual: Cualitativa Categorica 
- ExterCond: Cualitativa Categorica
- Foundation: Cualitativa Categorica
- BsmtQual: Cualitativa Ordinal
- BsmtCond: Cualitativa Categorica
- BsmtExposure: Cualitativa Categorica 
- BsmtFinType1: Cualitativa Categorica
- BsmtFinSF1: Cuantitativa Continua
- BsmtFinType2: Cualitativa Categorica
- BsmtFinSF2: Cuantitativa Continua
- BsmtUnfSF: Cuantitativa Continua
- TotalBsmtSF: Cuantitativa Continua
- Heating: Cualitativa Categorica
- HeatingQC: Cualitativa Categoriica
- CentralAir: Cualitativa Categorica
- Electrical: Cualitativa Categorica
- 1stFlrSF: Cuantitativa Continua
- 2ndFlrSF: Cuantitativa Continua
- LowQualFinSF: Cuantitativa Continua
- GrLivArea: Cuantitativa Continua
- BsmtFullBath: Cuantitativa Discreta
- BsmtHalfBath: Cuantitativa Discreta
- FullBath: Cuantitativa Discreta
- HalfBath: Cuantitativa Discreta
- Bedroom: Cuantitativa Discreta
- Kitchen: Kitchens above grade
- KitchenQual: Cualitativa Categorica
- TotRmsAbvGrd: Cuantitativa Discreta
- Functional: Cualitativa Categorica
- Fireplaces: Cuantitativa Discreta
- FireplaceQu: Cualitativa Categorica
- GarageType: Cualitativa Categorica		
- GarageYrBlt: Cuantitativa Discreta
- GarageFinish: Cualitativa Categorica
- GarageCars: Cuantitativa Discreta
- GarageArea: Cuantitativa Continua
- GarageQual: Cualitativa Categorica
- GarageCond: Cualitativa Categorica 
- PavedDrive: Cualitativa Categorica
- WoodDeckSF: Cuantitativa Continua
- OpenPorchSF: Cuantitativa Continua
- EnclosedPorch: Cuantitativa Continua
- 3SsnPorch: TCuantitativa Continua
- ScreenPorch: Cuantitativa Continua
- PoolArea: Cuantitativa Continua
- PoolQC: Cualitativa Categorica
- Fence: Cualitativa Categorica
- MiscFeature: Cualitativa Categorica
- MiscVal: Cuantitativa Discreta
- MoSold: Cuantitativa Discreta
- YrSold: Cuantitativa Discreta
- SaleType: Cualitativa Categorica
- SaleCondition: Cualitativa Categorica

*Antes de llevar a cabo el análisis se realiza una carga de los datos y se realizá una serie de preprocesamientos para que la información sea útil para el análisis como llenar con 0s o realizar las conversiones debidas a elementos tipo *NaN***

In [31]:
dataframe: pd.DataFrame = pd.read_csv("train.csv",  encoding='ISO-8859-1')

dataframe.columns
dataframe['PoolQC'] = dataframe['PoolQC'].fillna(0) # Se rellenan con 0 los na de PoolQC
dataframe['MasVnrType'] = dataframe['MasVnrType'].fillna('None') # Se rellenan con 'None' los na 'MasVnrType'
dataframe['FireplaceQu'] = dataframe['MasVnrType'].fillna('NA')
dataframe['Fence'] = dataframe['Fence'].fillna('NA')
dataframe['MiscFeature'] = dataframe['MiscFeature'].fillna('NA')
dataframe['LotFrontage'] = dataframe['LotFrontage'].fillna(0)
dataframe['Alley'] = dataframe['Alley'].fillna('NA')
#dataframe['GarageYrBlt'] = dataframe['GarageYrBlt'].fillna(dataframe['GarageYrBlt'].mean())
#dataframe['MasVnrArea'] = dataframe['MasVnrArea'].fillna(dataframe['MasVnrArea'].mean())

dataframe.drop(['Id'], axis=1, inplace=True) #Se elimina la columna Id

infoSumary = dataframe.info() #Mostrar información del tipo de variables utilizadas

#Extraccion de las columnas a utilizar para las pruebas de clustering y regresion lineal
df = dataframe
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MSSubClass     1460 non-null   int64  
 1   MSZoning       1460 non-null   object 
 2   LotFrontage    1460 non-null   float64
 3   LotArea        1460 non-null   int64  
 4   Street         1460 non-null   object 
 5   Alley          1460 non-null   object 
 6   LotShape       1460 non-null   object 
 7   LandContour    1460 non-null   object 
 8   Utilities      1460 non-null   object 
 9   LotConfig      1460 non-null   object 
 10  LandSlope      1460 non-null   object 
 11  Neighborhood   1460 non-null   object 
 12  Condition1     1460 non-null   object 
 13  Condition2     1460 non-null   object 
 14  BldgType       1460 non-null   object 
 15  HouseStyle     1460 non-null   object 
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0             60       RL         65.0     8450   Pave    NA      Reg   
1             20       RL         80.0     9600   Pave    NA      Reg   
2             60       RL         68.0    11250   Pave    NA      IR1   
3             70       RL         60.0     9550   Pave    NA      IR1   
4             60       RL         84.0    14260   Pave    NA      IR1   
...          ...      ...          ...      ...    ...   ...      ...   
1455          60       RL         62.0     7917   Pave    NA      Reg   
1456          20       RL         85.0    13175   Pave    NA      Reg   
1457          70       RL         66.0     9042   Pave    NA      Reg   
1458          20       RL         68.0     9717   Pave    NA      Reg   
1459          20       RL         75.0     9937   Pave    NA      Reg   

     LandContour Utilities LotConfig  ... PoolArea PoolQC  Fence MiscFeature  \
0            Lvl    AllPub    Inside  ...        0      0     NA          NA   
1            Lvl    AllPub       FR2  ...        0      0     NA          NA   
2            Lvl    AllPub    Inside  ...        0      0     NA          NA   
3            Lvl    AllPub    Corner  ...        0      0     NA          NA   
4            Lvl    AllPub       FR2  ...        0      0     NA          NA   
...          ...       ...       ...  ...      ...    ...    ...         ...   
1455         Lvl    AllPub    Inside  ...        0      0     NA          NA   
1456         Lvl    AllPub    Inside  ...        0      0  MnPrv          NA   
1457         Lvl    AllPub    Inside  ...        0      0  GdPrv        Shed   
1458         Lvl    AllPub    Inside  ...        0      0     NA          NA   
1459         Lvl    AllPub    Inside  ...        0      0     NA          NA   

     MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0          0      2    2008        WD         Normal     208500  
1          0      5    2007        WD         Normal     181500  
2          0      9    2008        WD         Normal     223500  
3          0      2    2006        WD        Abnorml     140000  
4          0     12    2008        WD         Normal     250000  
...      ...    ...     ...       ...            ...        ...  
1455       0      8    2007        WD         Normal     175000  
1456       0      2    2010        WD         Normal     210000  
1457    2500      5    2010        WD         Normal     266500  
1458       0      4    2010        WD         Normal     142125  
1459       0      6    2008        WD         Normal     147500  

[1460 rows x 80 columns]

Dentro del preprocesamiento de datos se convirtieron algunas variables cualitativas a su versión cuantitativas que se consideraron que pueden ser útiles para el análisis exploratorio.

In [32]:
new_columns = []
def change(variable):
    global df, new_columns
    count = 1
    new_columns.append(variable)
        
    if not pd.api.types.is_numeric_dtype(dataframe[variable]):
        dictValue = set(df[variable].unique())

        for i in dictValue:
            df[variable+'_'+str(i)]=dataframe[variable].apply(lambda x: 1 if x == i else 0)
            new_columns.append(variable+'_'+str(i))
        
        new_columns.remove(variable)

        
        dataframe.drop([variable], axis=1, inplace=True)
    

variables = [
    'MSSubClass', 'MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
    'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
    'OverallCond', 'YearBuilt', 'RoofStyle', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
    'ExterCond', 'Foundation', 'BsmtQual', 'BsmtExposure', 'BsmtFinType1', 'TotalBsmtSF', 'Heating',
    'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType',
    'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'BsmtCond', 'BsmtFinType2', 'RoofMatl',
    'ExterQual', 'SaleCondition'
]

for variable in variables:
    change(variable=variable)

df.columns

C:\Users\danar\AppData\Local\Temp\ipykernel_14512\282877624.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[variable+'_'+str(i)]=dataframe[variable].apply(lambda x: 1 if x == i else 0)
C:\Users\danar\AppData\Local\Temp\ipykernel_14512\282877624.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[variable+'_'+str(i)]=dataframe[variable].apply(lambda x: 1 if x == i else 0)
C:\Users\danar\AppData\Local\Temp\ipykernel_14512\282877624.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result o

Index(['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
       ...
       'ExterQual_Gd', 'ExterQual_TA', 'ExterQual_Fa', 'ExterQual_Ex',
       'SaleCondition_Family', 'SaleCondition_AdjLand',
       'SaleCondition_Abnorml', 'SaleCondition_Partial',
       'SaleCondition_Alloca', 'SaleCondition_Normal'],
      dtype='object', length=302)

In [33]:
df.head()

MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0          60         65.0     8450            7            5       2003   
1          20         80.0     9600            6            8       1976   
2          60         68.0    11250            7            5       2001   
3          70         60.0     9550            7            5       1915   
4          60         84.0    14260            8            5       2000   

   YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  ...  ExterQual_Gd  \
0          2003       196.0         706           0  ...             1   
1          1976         0.0         978           0  ...             0   
2          2002       162.0         486           0  ...             1   
3          1970         0.0         216           0  ...             0   
4          2000       350.0         655           0  ...             1   

   ExterQual_TA  ExterQual_Fa  ExterQual_Ex  SaleCondition_Family  \
0             0             0             0                     0   
1             1             0             0                     0   
2             0             0             0                     0   
3             1             0             0                     0   
4             0             0             0                     0   

   SaleCondition_AdjLand  SaleCondition_Abnorml  SaleCondition_Partial  \
0                      0                      0                      0   
1                      0                      0                      0   
2                      0                      0                      0   
3                      0                      1                      0   
4                      0                      0                      0   

   SaleCondition_Alloca  SaleCondition_Normal  
0                     0                     1  
1                     0                     1  
2                     0                     1  
3                     0                     0  
4                     0                     1  

[5 rows x 302 columns]

In [34]:
print('Se determina que el tamaño del dataframe con el que se está trabajando es de',len(dataframe),'datos (filas) incluyendo los encabezados de la tabla.')

Se determina que el tamaño del dataframe con el que se está trabajando es de 1460 datos (filas) incluyendo los encabezados de la tabla.


En este estudio, se decidió como convención realizar transformaciones de datos únicamente a aquellas columnas que cuentan con una cantidad de valores *NaN* mayor a 50 y son cuantitativas. Con este margen, únicamente dos columnas no fueron transformadas:

In [35]:
# Extrae la información relevante del resumen
info_data = {'Columna': [], 'Non-Null Count': [], 'Dtype': []}

for col in dataframe.columns:
    info_data['Columna'].append(col)
    info_data['Non-Null Count'].append(dataframe[col].count())
    info_data['Dtype'].append(dataframe[col].dtype)

# Crea un nuevo DataFrame a partir de la información extraída
info_df = pd.DataFrame(info_data)

info_df[info_df['Non-Null Count']<1460]

Columna  Non-Null Count    Dtype
7    MasVnrArea            1452  float64
24  GarageYrBlt            1379  float64

Se retiran las filas que contengan *NaN* en la columna de respuesta **SalePrice** debido a que es la variable principal que se está estudiando.

In [36]:
dataframe['SalePrice'] =dataframe['SalePrice'].dropna()
dataframe['SalePrice']

0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

# La variable respuesta es SalePrice, que  representa el precio de venta. 
    Como es una variable numerica, hay que hacerla categorica. 
    Luego evaluamos que tan balanceados estan los datos con respecto a esta

In [37]:
limite_inferior = df['SalePrice'].quantile(0.25)
limite_intermedio = df['SalePrice'].quantile(0.50)

In [38]:
def asignar_categoria(precio):
    if precio <= limite_inferior:
        return 'Económica'
    elif precio <= limite_intermedio:
        return 'Intermedia'
    else:
        return 'Cara'
    
df['categoria_precio'] = df['SalePrice'].apply(asignar_categoria)
toRegresion = df.pop('SalePrice')
df.head()

C:\Users\danar\AppData\Local\Temp\ipykernel_14512\210225139.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['categoria_precio'] = df['SalePrice'].apply(asignar_categoria)


MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0          60         65.0     8450            7            5       2003   
1          20         80.0     9600            6            8       1976   
2          60         68.0    11250            7            5       2001   
3          70         60.0     9550            7            5       1915   
4          60         84.0    14260            8            5       2000   

   YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  ...  ExterQual_TA  \
0          2003       196.0         706           0  ...             0   
1          1976         0.0         978           0  ...             1   
2          2002       162.0         486           0  ...             0   
3          1970         0.0         216           0  ...             1   
4          2000       350.0         655           0  ...             0   

   ExterQual_Fa  ExterQual_Ex  SaleCondition_Family  SaleCondition_AdjLand  \
0             0             0                     0                      0   
1             0             0                     0                      0   
2             0             0                     0                      0   
3             0             0                     0                      0   
4             0             0                     0                      0   

   SaleCondition_Abnorml  SaleCondition_Partial  SaleCondition_Alloca  \
0                      0                      0                     0   
1                      0                      0                     0   
2                      0                      0                     0   
3                      1                      0                     0   
4                      0                      0                     0   

   SaleCondition_Normal  categoria_precio  
0                     1              Cara  
1                     1              Cara  
2                     1              Cara  
3                     0        Intermedia  
4                     1              Cara  

[5 rows x 302 columns]

In [39]:
df.dropna()
df.groupby('categoria_precio').size()

categoria_precio
Cara          728
Económica     365
Intermedia    367
dtype: int64

## Algoritmo de Clasificación   
Vamos a dividir en conjuntos de entrenamiento (70%) y prueba (30%) los datos

In [40]:
target = df.pop('categoria_precio')
data = df

In [41]:
random.seed(123)
data_train, data_test,target_train, target_test = train_test_split(data, target,test_size=0.3,train_size=0.7)
data_train.columns
data_train = data_train.dropna()
target_train = target_train[data_train.index]  # Asegúrate de alinear los objetivos después de eliminar las filas
data_test = data_test.dropna()
target_test = target_test[data_test.index]  # Asegúrate de alinear los objetivos después de eliminar las filas


In [42]:
mlp = MLPClassifier(hidden_layer_sizes=(3,4), max_iter=1000)
mlp.fit(data_train,target_train)
y_pred = mlp.predict(data_test)
y_pred

array(['Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
      

In [43]:
cm = confusion_matrix(target_test,y_pred)
accuracy = accuracy_score(target_test,y_pred)
precision = precision_score(target_test, y_pred,average='micro')
recall =  recall_score(target_test, y_pred,average='micro')
f1 = f1_score(target_test,y_pred,average='micro')
print('Matriz de confusión\n',cm)
print('Accuracy: ',accuracy)
print('Precision: ', precision)
print('recall: ',recall)

Matriz de confusión
 [[236   0   0]
 [ 82   0   0]
 [ 99   0   0]]
Accuracy:  0.565947242206235
Precision:  0.565947242206235
recall:  0.565947242206235


In [44]:
mlp2 = MLPClassifier(hidden_layer_sizes=(5,2), activation='relu', max_iter=2000)
mlp2.fit(data_train,target_train)
y_pred2 = mlp2.predict(data_test)
X_pred2 = mlp2.predict(data_train)
y_pred2

array(['Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
      

In [45]:
cm2 = confusion_matrix(target_test,y_pred2)
accuracy2 = accuracy_score(target_test,y_pred2)
precision2 = precision_score(target_test, y_pred2,average='micro')
recall2 =  recall_score(target_test, y_pred2,average='micro')
f12 = f1_score(target_test,y_pred2,average='micro')
print('Matriz de confusión\n',cm2)
print('Accuracy: ',accuracy2)
print('Precision: ', precision2)
print('recall: ',recall2)

Matriz de confusión
 [[236   0   0]
 [ 82   0   0]
 [ 99   0   0]]
Accuracy:  0.565947242206235
Precision:  0.565947242206235
recall:  0.565947242206235


In [46]:
cm2 = confusion_matrix(target_train,X_pred2)
accuracy2 = accuracy_score(target_train,X_pred2)
precision2 = precision_score(target_train, X_pred2,average='micro')
recall2 =  recall_score(target_train, X_pred2,average='micro')
f12 = f1_score(target_train,X_pred2,average='micro')
print('Matriz de confusión\n',cm2)
print('Accuracy: ',accuracy2)
print('Precision: ', precision2)
print('recall: ',recall2)

Matriz de confusión
 [[481   0   0]
 [217   0   0]
 [255   0   0]]
Accuracy:  0.5047219307450157
Precision:  0.5047219307450157
recall:  0.5047219307450157


In [47]:
preprocesador_categorico = OneHotEncoder(handle_unknown="ignore")
preprocesador_numerico = StandardScaler()

In [48]:
#Creamos los selectores
selector_numericas = selector(dtype_exclude=object) #Seleccionamos todas las variables que no son Object
selector_categoricas = selector(dtype_include=object) #Seleccionamos todas las varibles de tipo object
#Seleccionamos las columnas que cumplen con los selectores pasándole los datos
numericas = selector_numericas(data)
categoricas = selector_categoricas(data)
#veamos que tan bien separó las variables
print("Numéricas: ",numericas)
print("Categóricas: ", categoricas)

Numéricas:  ['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'MSZoning_RM', 'MSZoning_RH', 'MSZoning_C (all)', 'MSZoning_RL', 'MSZoning_FV', 'Street_Pave', 'Street_Grvl', 'Alley_Pave', 'Alley_NA', 'Alley_Grvl', 'LotShape_IR1', 'LotShape_Reg', 'LotShape_IR2', 'LotShape_IR3', 'LandContour_HLS', 'LandContour_Low', 'LandContour_Lvl', 'LandContour_Bnk', 'Utilities_NoSeWa', 'Utilities_AllPub', 'LotConfig_FR2', 'LotConfig_FR3', 'LotConfig_CulDSac', 'LotConfig_Inside', 'LotConfig_Corner', 'LandSlope_Sev', 'LandSlope_Mod', 'LandSlope_Gtl', 'Neighborho

In [49]:
preprocesador = ColumnTransformer([
    ('one_hot_encoder',preprocesador_categorico,categoricas),
    ('standard_scaler',preprocesador_numerico, numericas)
])

In [50]:
mlpT = make_pipeline(preprocesador,MLPClassifier(activation="tanh",verbose=True,hidden_layer_sizes=(5,3)))
mlpT

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('one_hot_encoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  []),
                                                 ('standard_scaler',
                                                  StandardScaler(),
                                                  ['MSSubClass', 'LotFrontage',
                                                   'LotArea', 'OverallQual',
                                                   'OverallCond', 'YearBuilt',
                                                   'YearRemodAdd', 'MasVnrArea',
                                                   'BsmtFinSF1', 'BsmtFinSF2',
                                                   'BsmtUnfSF', 'TotalBsmtSF',
                                                   '1stFlrSF', '2ndFlrSF',
                                                   'LowQualFinSF', 'GrLivArea',
                                                   'BsmtFullBath',
                                                   'BsmtHalfBath', 'FullBath',
                                                   'HalfBath', 'BedroomAbvGr',
                                                   'KitchenAbvGr',
                                                   'TotRmsAbvGrd', 'Fireplaces',
                                                   'GarageYrBlt', 'GarageCars',
                                                   'GarageArea', 'WoodDeckSF',
                                                   'OpenPorchSF',
                                                   'EnclosedPorch', ...])])),
                ('mlpclassifier',
                 MLPClassifier(activation='tanh', hidden_layer_sizes=(5, 3),
                               verbose=True))])

In [51]:
mlpT.get_params().keys()

dict_keys(['memory', 'steps', 'verbose', 'columntransformer', 'mlpclassifier', 'columntransformer__n_jobs', 'columntransformer__remainder', 'columntransformer__sparse_threshold', 'columntransformer__transformer_weights', 'columntransformer__transformers', 'columntransformer__verbose', 'columntransformer__verbose_feature_names_out', 'columntransformer__one_hot_encoder', 'columntransformer__standard_scaler', 'columntransformer__one_hot_encoder__categories', 'columntransformer__one_hot_encoder__drop', 'columntransformer__one_hot_encoder__dtype', 'columntransformer__one_hot_encoder__feature_name_combiner', 'columntransformer__one_hot_encoder__handle_unknown', 'columntransformer__one_hot_encoder__max_categories', 'columntransformer__one_hot_encoder__min_frequency', 'columntransformer__one_hot_encoder__sparse_output', 'columntransformer__standard_scaler__copy', 'columntransformer__standard_scaler__with_mean', 'columntransformer__standard_scaler__with_std', 'mlpclassifier__activation', 'mlpcl

In [52]:
data_train, data_test, target_train, target_test = train_test_split(
    data, target, train_size=0.7,test_size=0.3)
print("Shape train",data_train.shape)
print("Shape test",data_test.shape)
data_train = data_train.dropna()
target_train = target_train[data_train.index]  # Asegúrate de alinear los objetivos después de eliminar las filas
data_test = data_test.dropna()
target_test = target_test[data_test.index]  # Asegúrate de alinear los objetivos después de eliminar las filas
data.isnull().sum()

Shape train (1021, 301)
Shape test (438, 301)


MSSubClass               0
LotFrontage              0
LotArea                  0
OverallQual              0
OverallCond              0
                        ..
SaleCondition_AdjLand    0
SaleCondition_Abnorml    0
SaleCondition_Partial    0
SaleCondition_Alloca     0
SaleCondition_Normal     0
Length: 301, dtype: int64

In [53]:
mlpT.fit(data_train,target_train)

Iteration 1, loss = 1.00406956
Iteration 2, loss = 0.93259270
Iteration 3, loss = 0.87655305
Iteration 4, loss = 0.83058600
Iteration 5, loss = 0.79326802
Iteration 6, loss = 0.76150870
Iteration 7, loss = 0.73374574
Iteration 8, loss = 0.71010253
Iteration 9, loss = 0.68870765
Iteration 10, loss = 0.66998651
Iteration 11, loss = 0.65267739
Iteration 12, loss = 0.63660031
Iteration 13, loss = 0.62156827
Iteration 14, loss = 0.60750061
Iteration 15, loss = 0.59371235
Iteration 16, loss = 0.58066108
Iteration 17, loss = 0.56841299
Iteration 18, loss = 0.55666585
Iteration 19, loss = 0.54562402
Iteration 20, loss = 0.53463115
Iteration 21, loss = 0.52490805
Iteration 22, loss = 0.51530433
Iteration 23, loss = 0.50637359
Iteration 24, loss = 0.49770182
Iteration 25, loss = 0.48965873
Iteration 26, loss = 0.48201879
Iteration 27, loss = 0.47491494
Iteration 28, loss = 0.46786742
Iteration 29, loss = 0.46116986
Iteration 30, loss = 0.45471135
Iteration 31, loss = 0.44846620
Iteration 32, los

C:\Users\danar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('one_hot_encoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  []),
                                                 ('standard_scaler',
                                                  StandardScaler(),
                                                  ['MSSubClass', 'LotFrontage',
                                                   'LotArea', 'OverallQual',
                                                   'OverallCond', 'YearBuilt',
                                                   'YearRemodAdd', 'MasVnrArea',
                                                   'BsmtFinSF1', 'BsmtFinSF2',
                                                   'BsmtUnfSF', 'TotalBsmtSF',
                                                   '1stFlrSF', '2ndFlrSF',
                                                   'LowQualFinSF', 'GrLivArea',
                                                   'BsmtFullBath',
                                                   'BsmtHalfBath', 'FullBath',
                                                   'HalfBath', 'BedroomAbvGr',
                                                   'KitchenAbvGr',
                                                   'TotRmsAbvGrd', 'Fireplaces',
                                                   'GarageYrBlt', 'GarageCars',
                                                   'GarageArea', 'WoodDeckSF',
                                                   'OpenPorchSF',
                                                   'EnclosedPorch', ...])])),
                ('mlpclassifier',
                 MLPClassifier(activation='tanh', hidden_layer_sizes=(5, 3),
                               verbose=True))])

In [54]:
ypredM = mlpT.predict(data_train)
cmT = confusion_matrix(target_train,ypredM)
accuracyT = accuracy_score(target_train,ypredM)
precisionT = precision_score(target_train, ypredM,average='micro')
recallT =  recall_score(target_train, ypredM,average='micro')
f1T = f1_score(target_train,ypredM,average='micro')
print('Matriz de confusión\n',cmT)
print('Accuracy: ',accuracyT)
print('Precision: ', precisionT)
print('recall: ',recallT)


Matriz de confusión
 [[499   0   2]
 [  0 204   2]
 [  3   2 253]]
Accuracy:  0.9906735751295337
Precision:  0.9906735751295337
recall:  0.9906735751295337


In [55]:
ypredM = mlpT.predict(data_test)
cmT = confusion_matrix(target_test,ypredM)
accuracyT = accuracy_score(target_test,ypredM)
precisionT = precision_score(target_test, ypredM,average='micro')
recallT =  recall_score(target_test, ypredM,average='micro')
f1T = f1_score(target_test,ypredM,average='micro')
print('Matriz de confusión\n',cmT)
print('Accuracy: ',accuracyT)
print('Precision: ', precisionT)
print('recall: ',recallT)


Matriz de confusión
 [[195   5  16]
 [  0  75  18]
 [ 15  25  56]]
Accuracy:  0.8049382716049382
Precision:  0.8049382716049382
recall:  0.8049382716049382


In [56]:
parametros_tun  = param_grid = {
    'mlpclassifier__max_iter': (100,200,500,1000),
    'mlpclassifier__learning_rate_init': (0.01, 0.1, 1,10),
    'mlpclassifier__hidden_layer_sizes':((3,2),(5,3),(10,2))}
model_grid_search = GridSearchCV(mlpT, param_grid=parametros_tun,
                                 n_jobs=2, cv=10) #Vamos a usar dos procesadores(n_jobs), y 10 k-folds
model_grid_search.fit(data_train, target_train)

Iteration 1, loss = 1.15366187
Iteration 2, loss = 0.93571789
Iteration 3, loss = 0.81491434
Iteration 4, loss = 0.72997677
Iteration 5, loss = 0.66709691
Iteration 6, loss = 0.61733408
Iteration 7, loss = 0.57501440
Iteration 8, loss = 0.54038499
Iteration 9, loss = 0.51146763
Iteration 10, loss = 0.48815112
Iteration 11, loss = 0.47029063
Iteration 12, loss = 0.45588279
Iteration 13, loss = 0.44436376
Iteration 14, loss = 0.43415387
Iteration 15, loss = 0.42605680
Iteration 16, loss = 0.41891091
Iteration 17, loss = 0.41287422
Iteration 18, loss = 0.40702551
Iteration 19, loss = 0.40120730
Iteration 20, loss = 0.39651684
Iteration 21, loss = 0.39099650
Iteration 22, loss = 0.38792632
Iteration 23, loss = 0.38527449
Iteration 24, loss = 0.38227965
Iteration 25, loss = 0.38038003
Iteration 26, loss = 0.37758586
Iteration 27, loss = 0.37546692
Iteration 28, loss = 0.37297429
Iteration 29, loss = 0.37062088
Iteration 30, loss = 0.36810700
Iteration 31, loss = 0.36553692
Iteration 32, los

GridSearchCV(cv=10,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('one_hot_encoder',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         []),
                                                                        ('standard_scaler',
                                                                         StandardScaler(),
                                                                         ['MSSubClass',
                                                                          'LotFrontage',
                                                                          'LotArea',
                                                                          'OverallQual',
                                                                          'OverallCond',
                                                                          'YearBuilt',
                                                                          'YearRemodAdd',
                                                                          'MasVnrArea',
                                                                          'BsmtFinSF1',
                                                                          'BsmtFinSF2',
                                                                          'BsmtUnfSF',
                                                                          'TotalBsmt...
                                                                          'GarageYrBlt',
                                                                          'GarageCars',
                                                                          'GarageArea',
                                                                          'WoodDeckSF',
                                                                          'OpenPorchSF',
                                                                          'EnclosedPorch', ...])])),
                                       ('mlpclassifier',
                                        MLPClassifier(activation='tanh',
                                                      hidden_layer_sizes=(5, 3),
                                                      verbose=True))]),
             n_jobs=2,
             param_grid={'mlpclassifier__hidden_layer_sizes': ((3, 2), (5, 3),
                                                               (10, 2)),
                         'mlpclassifier__learning_rate_init': (0.01, 0.1, 1,
                                                               10),
                         'mlpclassifier__max_iter': (100, 200, 500, 1000)})

In [57]:
ypredMT = model_grid_search.predict(data_train)
cmTM = confusion_matrix(target_train,ypredMT)
accuracyTM = accuracy_score(target_train,ypredMT)
precisionTM = precision_score(target_train, ypredMT,average='micro')
recallTM = recall_score(target_train, ypredMT,average='micro')
f1TM = f1_score(target_train,ypredMT,average='micro')
print('Matriz de confusión\n',cmT)
print('Accuracy: ',accuracyT)
print('Precision: ', precisionT)
print('recall: ',recallT)

Matriz de confusión
 [[195   5  16]
 [  0  75  18]
 [ 15  25  56]]
Accuracy:  0.8049382716049382
Precision:  0.8049382716049382
recall:  0.8049382716049382


In [58]:
ypredMT = model_grid_search.predict(data_test)
cmTM = confusion_matrix(target_test,ypredMT)
accuracyTM = accuracy_score(target_test,ypredMT)
precisionTM = precision_score(target_test, ypredMT,average='micro')
recallTM = recall_score(target_test, ypredMT,average='micro')
f1TM = f1_score(target_test,ypredMT,average='micro')
print('Matriz de confusión\n',cmT)
print('Accuracy: ',accuracyT)
print('Precision: ', precisionT)
print('recall: ',recallT)

Matriz de confusión
 [[195   5  16]
 [  0  75  18]
 [ 15  25  56]]
Accuracy:  0.8049382716049382
Precision:  0.8049382716049382
recall:  0.8049382716049382
