<a href="https://colab.research.google.com/github/Dahernandezsilve/HT1MD/blob/main/HT_1_An%C3%A1lisis_Exploratorio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Universidad del Valle de Guatemala
18 Avenida 11-95 Guatemala      
Departamento de Computación     
Facultad de Ingeniería       
Minería de Datos Sección 10         
Fecha de entrega: 29/01/2024        

Grupo 6 | Integrantes:
- Diego Alexander Hernández Silvestre 21270
- Linda Inés Jimenez Vides 21169
- Daniel Armando Valdez Reyes 21240

## HDT8 - RNA
Para realizar una exploración inicial del conjunto de datos, se prodeció a realizar un resumen de la información proporcionada en el dataset del archivo "*train.csv*. A continuación se muestran los resultados: 

*Primero se importan todas la librerías requeridas para llevar a cabo el análisis*

In [463]:
import pandas as pd
from scipy.stats import shapiro, ks_2samp, anderson
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from typing import *
import matplotlib.pyplot as plt
from sklearn import datasets
import sklearn as sklearn
import sklearn.cluster as cluster
import sklearn.metrics as metrics
from sklearn.preprocessing import StandardScaler
import scipy.cluster.hierarchy as sch
import skfuzzy as fuzz
import pylab
import sklearn.mixture as mixture
import pyclustertend 
import random
import statsmodels.api as sm
import statsmodels.stats.diagnostic as smd
from sklearn.linear_model import LinearRegression
from sklearn import datasets
from sklearn.model_selection import train_test_split, cross_val_predict
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.linear_model import Ridge
import seaborn as sns
import statsmodels.api as sm
from statsmodels.graphics.gofplots import qqplot
from yellowbrick.regressor import ResidualsPlot
import scipy.stats as stats
import statsmodels.stats.diagnostic as diag
from scipy.stats import normaltest

from sklearn.svm import SVC
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import root_mean_squared_error
import matplotlib.pyplot as plt
import numpy as np
import random
import statsmodels.api as sm
import statsmodels.stats.diagnostic as smd
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
import seaborn as sns
import statsmodels.api as sm
import scipy.stats as stats
import statsmodels.stats.diagnostic as diag
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

from sklearn.compose import make_column_selector as selector #Para seleccionar de forma automática las variables numéricas y categóricas
from sklearn.preprocessing import OneHotEncoder #Para codificar las variables categóricas usando dummies
from sklearn.preprocessing import StandardScaler #Para normalizar las variables numéricas
from sklearn.compose import ColumnTransformer #Modifica las columnas usando los preprocesadores
from sklearn.pipeline import make_pipeline #Planifica una secuencia de procesos
from sklearn import set_config #Para mostrar graficamente el pipeline
from sklearn.model_selection import GridSearchCV

set_config(display='diagram')
#Metrics
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score ,precision_score,recall_score,f1_score

Se lleva a cabo un análisis identificando los tipos de variables involucradas:
## Descripcion de variables
- MSSubClass: Cuantitativa Discreta
- MSZoning: Cualitativa Categorica	
- LotFrontage: Cuantitativa Medible
- LotArea: Cuantitativa Medible
- Street: Cualitativa Categorica
- Alley: Cualitativa Categorica
- LotShape: Cualitativa Categorica       
- LandContour: Cualitativa Categorica
- Utilities: Cualitativa Categorica		
- LotConfig: Cualitativa Categorica
- LandSlope: Cualitativa Categorica 
- Neighborhood: Cualitativa Categorica
- Condition1: Cualitativa Categorica
- Condition2: Cualitativa Categorica
- BldgType: Cualitativa Categorica
- HouseStyle: Cualitativa Categorica 
- OverallQual: Cuantitativa Discreta
- OverallCond: Cuantitativa Discreta
- YearBuilt: Cuantitativa Discreta
- YearRemodAdd: Cuantitativa Discreta
- RoofStyle: Cualitativa Categorica
- RoofMatl: Cualitativa Categorica
- Exterior1st: Cualitativa Categorica
- Exterior2nd: Cualitativa Categorica
- MasVnrType: Cualitativa Categorica
- MasVnrArea: Cuantitativa Continua
- ExterQual: Cualitativa Categorica 
- ExterCond: Cualitativa Categorica
- Foundation: Cualitativa Categorica
- BsmtQual: Cualitativa Ordinal
- BsmtCond: Cualitativa Categorica
- BsmtExposure: Cualitativa Categorica 
- BsmtFinType1: Cualitativa Categorica
- BsmtFinSF1: Cuantitativa Continua
- BsmtFinType2: Cualitativa Categorica
- BsmtFinSF2: Cuantitativa Continua
- BsmtUnfSF: Cuantitativa Continua
- TotalBsmtSF: Cuantitativa Continua
- Heating: Cualitativa Categorica
- HeatingQC: Cualitativa Categoriica
- CentralAir: Cualitativa Categorica
- Electrical: Cualitativa Categorica
- 1stFlrSF: Cuantitativa Continua
- 2ndFlrSF: Cuantitativa Continua
- LowQualFinSF: Cuantitativa Continua
- GrLivArea: Cuantitativa Continua
- BsmtFullBath: Cuantitativa Discreta
- BsmtHalfBath: Cuantitativa Discreta
- FullBath: Cuantitativa Discreta
- HalfBath: Cuantitativa Discreta
- Bedroom: Cuantitativa Discreta
- Kitchen: Kitchens above grade
- KitchenQual: Cualitativa Categorica
- TotRmsAbvGrd: Cuantitativa Discreta
- Functional: Cualitativa Categorica
- Fireplaces: Cuantitativa Discreta
- FireplaceQu: Cualitativa Categorica
- GarageType: Cualitativa Categorica		
- GarageYrBlt: Cuantitativa Discreta
- GarageFinish: Cualitativa Categorica
- GarageCars: Cuantitativa Discreta
- GarageArea: Cuantitativa Continua
- GarageQual: Cualitativa Categorica
- GarageCond: Cualitativa Categorica 
- PavedDrive: Cualitativa Categorica
- WoodDeckSF: Cuantitativa Continua
- OpenPorchSF: Cuantitativa Continua
- EnclosedPorch: Cuantitativa Continua
- 3SsnPorch: TCuantitativa Continua
- ScreenPorch: Cuantitativa Continua
- PoolArea: Cuantitativa Continua
- PoolQC: Cualitativa Categorica
- Fence: Cualitativa Categorica
- MiscFeature: Cualitativa Categorica
- MiscVal: Cuantitativa Discreta
- MoSold: Cuantitativa Discreta
- YrSold: Cuantitativa Discreta
- SaleType: Cualitativa Categorica
- SaleCondition: Cualitativa Categorica

*Antes de llevar a cabo el análisis se realiza una carga de los datos y se realizá una serie de preprocesamientos para que la información sea útil para el análisis como llenar con 0s o realizar las conversiones debidas a elementos tipo *NaN***

In [464]:
dataframe: pd.DataFrame = pd.read_csv("train.csv",  encoding='ISO-8859-1')

dataframe.columns
dataframe['PoolQC'] = dataframe['PoolQC'].fillna(0) # Se rellenan con 0 los na de PoolQC
dataframe['MasVnrType'] = dataframe['MasVnrType'].fillna('None') # Se rellenan con 'None' los na 'MasVnrType'
dataframe['FireplaceQu'] = dataframe['MasVnrType'].fillna('NA')
dataframe['Fence'] = dataframe['Fence'].fillna('NA')
dataframe['MiscFeature'] = dataframe['MiscFeature'].fillna('NA')
dataframe['LotFrontage'] = dataframe['LotFrontage'].fillna(0)
dataframe['Alley'] = dataframe['Alley'].fillna('NA')
#dataframe['GarageYrBlt'] = dataframe['GarageYrBlt'].fillna(dataframe['GarageYrBlt'].mean())
#dataframe['MasVnrArea'] = dataframe['MasVnrArea'].fillna(dataframe['MasVnrArea'].mean())

dataframe.drop(['Id'], axis=1, inplace=True) #Se elimina la columna Id

infoSumary = dataframe.info() #Mostrar información del tipo de variables utilizadas

#Extraccion de las columnas a utilizar para las pruebas de clustering y regresion lineal
df = dataframe
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MSSubClass     1460 non-null   int64  
 1   MSZoning       1460 non-null   object 
 2   LotFrontage    1460 non-null   float64
 3   LotArea        1460 non-null   int64  
 4   Street         1460 non-null   object 
 5   Alley          1460 non-null   object 
 6   LotShape       1460 non-null   object 
 7   LandContour    1460 non-null   object 
 8   Utilities      1460 non-null   object 
 9   LotConfig      1460 non-null   object 
 10  LandSlope      1460 non-null   object 
 11  Neighborhood   1460 non-null   object 
 12  Condition1     1460 non-null   object 
 13  Condition2     1460 non-null   object 
 14  BldgType       1460 non-null   object 
 15  HouseStyle     1460 non-null   object 
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0             60       RL         65.0     8450   Pave    NA      Reg   
1             20       RL         80.0     9600   Pave    NA      Reg   
2             60       RL         68.0    11250   Pave    NA      IR1   
3             70       RL         60.0     9550   Pave    NA      IR1   
4             60       RL         84.0    14260   Pave    NA      IR1   
...          ...      ...          ...      ...    ...   ...      ...   
1455          60       RL         62.0     7917   Pave    NA      Reg   
1456          20       RL         85.0    13175   Pave    NA      Reg   
1457          70       RL         66.0     9042   Pave    NA      Reg   
1458          20       RL         68.0     9717   Pave    NA      Reg   
1459          20       RL         75.0     9937   Pave    NA      Reg   

     LandContour Utilities LotConfig  ... PoolArea PoolQC  Fence MiscFeature  \
0            Lvl    AllPub    Inside  ...        0      0     NA          NA   
1            Lvl    AllPub       FR2  ...        0      0     NA          NA   
2            Lvl    AllPub    Inside  ...        0      0     NA          NA   
3            Lvl    AllPub    Corner  ...        0      0     NA          NA   
4            Lvl    AllPub       FR2  ...        0      0     NA          NA   
...          ...       ...       ...  ...      ...    ...    ...         ...   
1455         Lvl    AllPub    Inside  ...        0      0     NA          NA   
1456         Lvl    AllPub    Inside  ...        0      0  MnPrv          NA   
1457         Lvl    AllPub    Inside  ...        0      0  GdPrv        Shed   
1458         Lvl    AllPub    Inside  ...        0      0     NA          NA   
1459         Lvl    AllPub    Inside  ...        0      0     NA          NA   

     MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0          0      2    2008        WD         Normal     208500  
1          0      5    2007        WD         Normal     181500  
2          0      9    2008        WD         Normal     223500  
3          0      2    2006        WD        Abnorml     140000  
4          0     12    2008        WD         Normal     250000  
...      ...    ...     ...       ...            ...        ...  
1455       0      8    2007        WD         Normal     175000  
1456       0      2    2010        WD         Normal     210000  
1457    2500      5    2010        WD         Normal     266500  
1458       0      4    2010        WD         Normal     142125  
1459       0      6    2008        WD         Normal     147500  

[1460 rows x 80 columns]

Dentro del preprocesamiento de datos se convirtieron algunas variables cualitativas a su versión cuantitativas que se consideraron que pueden ser útiles para el análisis exploratorio.

In [465]:
new_columns = []
def change(variable):
    global df, new_columns
    count = 1
    new_columns.append(variable)
        
    if not pd.api.types.is_numeric_dtype(dataframe[variable]):
        dictValue = set(df[variable].unique())

        for i in dictValue:
            df[variable+'_'+str(i)]=dataframe[variable].apply(lambda x: 1 if x == i else 0)
            new_columns.append(variable+'_'+str(i))
        
        new_columns.remove(variable)

        
        dataframe.drop([variable], axis=1, inplace=True)
    

variables = [
    'MSSubClass', 'MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
    'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
    'OverallCond', 'YearBuilt', 'RoofStyle', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
    'ExterCond', 'Foundation', 'BsmtQual', 'BsmtExposure', 'BsmtFinType1', 'TotalBsmtSF', 'Heating',
    'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType',
    'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'BsmtCond', 'BsmtFinType2', 'RoofMatl',
    'ExterQual', 'SaleCondition'
]

for variable in variables:
    change(variable=variable)

df.columns

C:\Users\lijv1\AppData\Local\Temp\ipykernel_35944\282877624.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[variable+'_'+str(i)]=dataframe[variable].apply(lambda x: 1 if x == i else 0)
C:\Users\lijv1\AppData\Local\Temp\ipykernel_35944\282877624.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[variable+'_'+str(i)]=dataframe[variable].apply(lambda x: 1 if x == i else 0)
C:\Users\lijv1\AppData\Local\Temp\ipykernel_35944\282877624.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result o

C:\Users\lijv1\AppData\Local\Temp\ipykernel_35944\282877624.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[variable+'_'+str(i)]=dataframe[variable].apply(lambda x: 1 if x == i else 0)
C:\Users\lijv1\AppData\Local\Temp\ipykernel_35944\282877624.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[variable+'_'+str(i)]=dataframe[variable].apply(lambda x: 1 if x == i else 0)
C:\Users\lijv1\AppData\Local\Temp\ipykernel_35944\282877624.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result o

Index(['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
       ...
       'ExterQual_Ex', 'ExterQual_TA', 'ExterQual_Fa', 'ExterQual_Gd',
       'SaleCondition_Normal', 'SaleCondition_Family', 'SaleCondition_AdjLand',
       'SaleCondition_Alloca', 'SaleCondition_Abnorml',
       'SaleCondition_Partial'],
      dtype='object', length=302)

In [466]:
df.head()

MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0          60         65.0     8450            7            5       2003   
1          20         80.0     9600            6            8       1976   
2          60         68.0    11250            7            5       2001   
3          70         60.0     9550            7            5       1915   
4          60         84.0    14260            8            5       2000   

   YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  ...  ExterQual_Ex  \
0          2003       196.0         706           0  ...             0   
1          1976         0.0         978           0  ...             0   
2          2002       162.0         486           0  ...             0   
3          1970         0.0         216           0  ...             0   
4          2000       350.0         655           0  ...             0   

   ExterQual_TA  ExterQual_Fa  ExterQual_Gd  SaleCondition_Normal  \
0             0             0             1                     1   
1             1             0             0                     1   
2             0             0             1                     1   
3             1             0             0                     0   
4             0             0             1                     1   

   SaleCondition_Family  SaleCondition_AdjLand  SaleCondition_Alloca  \
0                     0                      0                     0   
1                     0                      0                     0   
2                     0                      0                     0   
3                     0                      0                     0   
4                     0                      0                     0   

   SaleCondition_Abnorml  SaleCondition_Partial  
0                      0                      0  
1                      0                      0  
2                      0                      0  
3                      1                      0  
4                      0                      0  

[5 rows x 302 columns]

In [467]:
print('Se determina que el tamaño del dataframe con el que se está trabajando es de',len(dataframe),'datos (filas) incluyendo los encabezados de la tabla.')

Se determina que el tamaño del dataframe con el que se está trabajando es de 1460 datos (filas) incluyendo los encabezados de la tabla.


En este estudio, se decidió como convención realizar transformaciones de datos únicamente a aquellas columnas que cuentan con una cantidad de valores *NaN* mayor a 50 y son cuantitativas. Con este margen, únicamente dos columnas no fueron transformadas:

In [468]:
# Extrae la información relevante del resumen
info_data = {'Columna': [], 'Non-Null Count': [], 'Dtype': []}

for col in dataframe.columns:
    info_data['Columna'].append(col)
    info_data['Non-Null Count'].append(dataframe[col].count())
    info_data['Dtype'].append(dataframe[col].dtype)

# Crea un nuevo DataFrame a partir de la información extraída
info_df = pd.DataFrame(info_data)

info_df[info_df['Non-Null Count']<1460]

Columna  Non-Null Count    Dtype
7    MasVnrArea            1452  float64
24  GarageYrBlt            1379  float64

Se retiran las filas que contengan *NaN* en la columna de respuesta **SalePrice** debido a que es la variable principal que se está estudiando.

In [469]:
dataframe['SalePrice'] =dataframe['SalePrice'].dropna()
dataframe['SalePrice']

0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

# La variable respuesta es SalePrice, que  representa el precio de venta. 
    Como es una variable numerica, hay que hacerla categorica. 
    Luego evaluamos que tan balanceados estan los datos con respecto a esta

In [470]:
limite_inferior = df['SalePrice'].quantile(0.25)
limite_intermedio = df['SalePrice'].quantile(0.50)

In [471]:
def asignar_categoria(precio):
    if precio <= limite_inferior:
        return 'Económica'
    elif precio <= limite_intermedio:
        return 'Intermedia'
    else:
        return 'Cara'
    
df['categoria_precio'] = df['SalePrice'].apply(asignar_categoria)
toRegresion = df.pop('SalePrice')
df.head()

C:\Users\lijv1\AppData\Local\Temp\ipykernel_35944\210225139.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['categoria_precio'] = df['SalePrice'].apply(asignar_categoria)


MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0          60         65.0     8450            7            5       2003   
1          20         80.0     9600            6            8       1976   
2          60         68.0    11250            7            5       2001   
3          70         60.0     9550            7            5       1915   
4          60         84.0    14260            8            5       2000   

   YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  ...  ExterQual_TA  \
0          2003       196.0         706           0  ...             0   
1          1976         0.0         978           0  ...             1   
2          2002       162.0         486           0  ...             0   
3          1970         0.0         216           0  ...             1   
4          2000       350.0         655           0  ...             0   

   ExterQual_Fa  ExterQual_Gd  SaleCondition_Normal  SaleCondition_Family  \
0             0             1                     1                     0   
1             0             0                     1                     0   
2             0             1                     1                     0   
3             0             0                     0                     0   
4             0             1                     1                     0   

   SaleCondition_AdjLand  SaleCondition_Alloca  SaleCondition_Abnorml  \
0                      0                     0                      0   
1                      0                     0                      0   
2                      0                     0                      0   
3                      0                     0                      1   
4                      0                     0                      0   

   SaleCondition_Partial  categoria_precio  
0                      0              Cara  
1                      0              Cara  
2                      0              Cara  
3                      0        Intermedia  
4                      0              Cara  

[5 rows x 302 columns]

In [472]:
df.dropna()
df.groupby('categoria_precio').size()

categoria_precio
Cara          728
Económica     365
Intermedia    367
dtype: int64

## Algoritmo de Clasificación   
Vamos a dividir en conjuntos de entrenamiento (70%) y prueba (30%) los datos

In [473]:
target = df.pop('categoria_precio')
data = df

In [474]:
random.seed(123)
data_train, data_test,target_train, target_test = train_test_split(data, target,test_size=0.3,train_size=0.7)
data_train.columns
data_train = data_train.dropna()
target_train = target_train[data_train.index]  # Asegúrate de alinear los objetivos después de eliminar las filas
data_test = data_test.dropna()
target_test = target_test[data_test.index]  # Asegúrate de alinear los objetivos después de eliminar las filas


In [475]:
mlp = MLPClassifier(hidden_layer_sizes=(3,4), max_iter=1000)
mlp.fit(data_train,target_train)
y_pred = mlp.predict(data_test)
y_pred

array(['Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
      

In [476]:
cm = confusion_matrix(target_test,y_pred)
accuracy = accuracy_score(target_test,y_pred)
precision = precision_score(target_test, y_pred,average='micro')
recall =  recall_score(target_test, y_pred,average='micro')
f1 = f1_score(target_test,y_pred,average='micro')
print('Matriz de confusión\n',cm)
print('Accuracy: ',accuracy)
print('Precision: ', precision)
print('recall: ',recall)

Matriz de confusión
 [[214   0   0]
 [ 93   0   0]
 [101   0   0]]
Accuracy:  0.5245098039215687
Precision:  0.5245098039215687
recall:  0.5245098039215687


In [477]:
mlp2 = MLPClassifier(hidden_layer_sizes=(5,2), activation='relu', max_iter=2000)
mlp2.fit(data_train,target_train)
y_pred2 = mlp2.predict(data_test)
X_pred2 = mlp2.predict(data_train)
y_pred2

array(['Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
       'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara', 'Cara',
      

In [478]:
cm2 = confusion_matrix(target_test,y_pred2)
accuracy2 = accuracy_score(target_test,y_pred2)
precision2 = precision_score(target_test, y_pred2,average='micro')
recall2 =  recall_score(target_test, y_pred2,average='micro')
f12 = f1_score(target_test,y_pred2,average='micro')
print('Matriz de confusión\n',cm2)
print('Accuracy: ',accuracy2)
print('Precision: ', precision2)
print('recall: ',recall2)

Matriz de confusión
 [[214   0   0]
 [ 93   0   0]
 [101   0   0]]
Accuracy:  0.5245098039215687
Precision:  0.5245098039215687
recall:  0.5245098039215687


In [479]:
cm2 = confusion_matrix(target_train,X_pred2)
accuracy2 = accuracy_score(target_train,X_pred2)
precision2 = precision_score(target_train, X_pred2,average='micro')
recall2 =  recall_score(target_train, X_pred2,average='micro')
f12 = f1_score(target_train,X_pred2,average='micro')
print('Matriz de confusión\n',cm2)
print('Accuracy: ',accuracy2)
print('Precision: ', precision2)
print('recall: ',recall2)

Matriz de confusión
 [[503   0   0]
 [205   0   0]
 [254   0   0]]
Accuracy:  0.5228690228690228
Precision:  0.5228690228690228
recall:  0.5228690228690228


In [480]:
preprocesador_categorico = OneHotEncoder(handle_unknown="ignore")
preprocesador_numerico = StandardScaler()

In [481]:
#Creamos los selectores
selector_numericas = selector(dtype_exclude=object) #Seleccionamos todas las variables que no son Object
selector_categoricas = selector(dtype_include=object) #Seleccionamos todas las varibles de tipo object
#Seleccionamos las columnas que cumplen con los selectores pasándole los datos
numericas = selector_numericas(data)
categoricas = selector_categoricas(data)
#veamos que tan bien separó las variables
print("Numéricas: ",numericas)
print("Categóricas: ", categoricas)

Numéricas:  ['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'MSZoning_C (all)', 'MSZoning_RH', 'MSZoning_RL', 'MSZoning_RM', 'MSZoning_FV', 'Street_Grvl', 'Street_Pave', 'Alley_Grvl', 'Alley_Pave', 'Alley_NA', 'LotShape_IR1', 'LotShape_IR3', 'LotShape_Reg', 'LotShape_IR2', 'LandContour_Bnk', 'LandContour_Low', 'LandContour_Lvl', 'LandContour_HLS', 'Utilities_NoSeWa', 'Utilities_AllPub', 'LotConfig_FR2', 'LotConfig_FR3', 'LotConfig_Inside', 'LotConfig_Corner', 'LotConfig_CulDSac', 'LandSlope_Sev', 'LandSlope_Gtl', 'LandSlope_Mod', 'Neighborho

In [482]:
preprocesador = ColumnTransformer([
    ('one_hot_encoder',preprocesador_categorico,categoricas),
    ('standard_scaler',preprocesador_numerico, numericas)
])

## Modelo 1 RNA

In [483]:
mlpT = make_pipeline(preprocesador,MLPClassifier(activation="tanh",verbose=True,hidden_layer_sizes=(5,3)))
mlpT

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('one_hot_encoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  []),
                                                 ('standard_scaler',
                                                  StandardScaler(),
                                                  ['MSSubClass', 'LotFrontage',
                                                   'LotArea', 'OverallQual',
                                                   'OverallCond', 'YearBuilt',
                                                   'YearRemodAdd', 'MasVnrArea',
                                                   'BsmtFinSF1', 'BsmtFinSF2',
                                                   'BsmtUnfSF', 'TotalBsmtSF',
                                                   '1stFlrSF', '2ndFlrSF',
                                                   'LowQualFinSF', 'GrLivArea',
                                                   'BsmtFullBath',
                                                   'BsmtHalfBath', 'FullBath',
                                                   'HalfBath', 'BedroomAbvGr',
                                                   'KitchenAbvGr',
                                                   'TotRmsAbvGrd', 'Fireplaces',
                                                   'GarageYrBlt', 'GarageCars',
                                                   'GarageArea', 'WoodDeckSF',
                                                   'OpenPorchSF',
                                                   'EnclosedPorch', ...])])),
                ('mlpclassifier',
                 MLPClassifier(activation='tanh', hidden_layer_sizes=(5, 3),
                               verbose=True))])

In [484]:
mlpT.get_params().keys()

dict_keys(['memory', 'steps', 'verbose', 'columntransformer', 'mlpclassifier', 'columntransformer__n_jobs', 'columntransformer__remainder', 'columntransformer__sparse_threshold', 'columntransformer__transformer_weights', 'columntransformer__transformers', 'columntransformer__verbose', 'columntransformer__verbose_feature_names_out', 'columntransformer__one_hot_encoder', 'columntransformer__standard_scaler', 'columntransformer__one_hot_encoder__categories', 'columntransformer__one_hot_encoder__drop', 'columntransformer__one_hot_encoder__dtype', 'columntransformer__one_hot_encoder__feature_name_combiner', 'columntransformer__one_hot_encoder__handle_unknown', 'columntransformer__one_hot_encoder__max_categories', 'columntransformer__one_hot_encoder__min_frequency', 'columntransformer__one_hot_encoder__sparse_output', 'columntransformer__standard_scaler__copy', 'columntransformer__standard_scaler__with_mean', 'columntransformer__standard_scaler__with_std', 'mlpclassifier__activation', 'mlpcl

In [485]:
data_train, data_test, target_train, target_test = train_test_split(
    data, target, train_size=0.7,test_size=0.3)
print("Shape train",data_train.shape)
print("Shape test",data_test.shape)
data_train = data_train.dropna()
target_train = target_train[data_train.index]  # Asegúrate de alinear los objetivos después de eliminar las filas
data_test = data_test.dropna()
target_test = target_test[data_test.index]  # Asegúrate de alinear los objetivos después de eliminar las filas
data.isnull().sum()

Shape train (1021, 301)
Shape test (438, 301)


MSSubClass               0
LotFrontage              0
LotArea                  0
OverallQual              0
OverallCond              0
                        ..
SaleCondition_Family     0
SaleCondition_AdjLand    0
SaleCondition_Alloca     0
SaleCondition_Abnorml    0
SaleCondition_Partial    0
Length: 301, dtype: int64

In [486]:
mlpT.fit(data_train,target_train)

Iteration 1, loss = 1.19590773
Iteration 2, loss = 1.10787230
Iteration 3, loss = 1.03626982
Iteration 4, loss = 0.97838832
Iteration 5, loss = 0.93128490
Iteration 6, loss = 0.89175260
Iteration 7, loss = 0.85894620
Iteration 8, loss = 0.82945005
Iteration 9, loss = 0.80371649
Iteration 10, loss = 0.78036198
Iteration 11, loss = 0.75889117
Iteration 12, loss = 0.73895558
Iteration 13, loss = 0.71968344
Iteration 14, loss = 0.70227457
Iteration 15, loss = 0.68510991
Iteration 16, loss = 0.66839350
Iteration 17, loss = 0.65323094
Iteration 18, loss = 0.63839739
Iteration 19, loss = 0.62418312
Iteration 20, loss = 0.61065473
Iteration 21, loss = 0.59809439
Iteration 22, loss = 0.58590922
Iteration 23, loss = 0.57433215
Iteration 24, loss = 0.56299574
Iteration 25, loss = 0.55195891
Iteration 26, loss = 0.54171160
Iteration 27, loss = 0.53181658
Iteration 28, loss = 0.52231998
Iteration 29, loss = 0.51328581
Iteration 30, loss = 0.50512254
Iteration 31, loss = 0.49700949
Iteration 32, los

c:\Users\lijv1\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('one_hot_encoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  []),
                                                 ('standard_scaler',
                                                  StandardScaler(),
                                                  ['MSSubClass', 'LotFrontage',
                                                   'LotArea', 'OverallQual',
                                                   'OverallCond', 'YearBuilt',
                                                   'YearRemodAdd', 'MasVnrArea',
                                                   'BsmtFinSF1', 'BsmtFinSF2',
                                                   'BsmtUnfSF', 'TotalBsmtSF',
                                                   '1stFlrSF', '2ndFlrSF',
                                                   'LowQualFinSF', 'GrLivArea',
                                                   'BsmtFullBath',
                                                   'BsmtHalfBath', 'FullBath',
                                                   'HalfBath', 'BedroomAbvGr',
                                                   'KitchenAbvGr',
                                                   'TotRmsAbvGrd', 'Fireplaces',
                                                   'GarageYrBlt', 'GarageCars',
                                                   'GarageArea', 'WoodDeckSF',
                                                   'OpenPorchSF',
                                                   'EnclosedPorch', ...])])),
                ('mlpclassifier',
                 MLPClassifier(activation='tanh', hidden_layer_sizes=(5, 3),
                               verbose=True))])

In [487]:
ypredM = mlpT.predict(data_train)
cmT = confusion_matrix(target_train,ypredM)
accuracyT = accuracy_score(target_train,ypredM)
precisionT = precision_score(target_train, ypredM,average='micro')
recallT =  recall_score(target_train, ypredM,average='micro')
f1T = f1_score(target_train,ypredM,average='micro')
print('Matriz de confusión\n',cmT)
print('Accuracy: ',accuracyT)
print('Precision: ', precisionT)
print('recall: ',recallT)


Matriz de confusión
 [[496   2   2]
 [  0 209   5]
 [  3   1 242]]
Accuracy:  0.9864583333333333
Precision:  0.9864583333333333
recall:  0.9864583333333333


In [488]:
ypredM = mlpT.predict(data_test)
cmT = confusion_matrix(target_test,ypredM)
accuracyT = accuracy_score(target_test,ypredM)
precisionT = precision_score(target_test, ypredM,average='micro')
recallT =  recall_score(target_test, ypredM,average='micro')
f1T = f1_score(target_test,ypredM,average='micro')
print('Matriz de confusión\n',cmT)
print('Accuracy: ',accuracyT)
print('Precision: ', precisionT)
print('recall: ',recallT)


Matriz de confusión
 [[198   8  10]
 [  2  57  26]
 [ 14  30  65]]
Accuracy:  0.7804878048780488
Precision:  0.7804878048780488
recall:  0.7804878048780488


## Tuneo de Parametros

In [489]:
parametros_tun  = param_grid = {
    'mlpclassifier__max_iter': (100,200,500,1000),
    'mlpclassifier__learning_rate_init': (0.01, 0.1, 1,10),
    'mlpclassifier__hidden_layer_sizes':((3,2),(5,3),(10,2))}
model_grid_search = GridSearchCV(mlpT, param_grid=parametros_tun,
                                 n_jobs=2, cv=10) #Vamos a usar dos procesadores(n_jobs), y 10 k-folds
model_grid_search.fit(data_train, target_train)

Iteration 1, loss = 0.91727418
Iteration 2, loss = 0.62672726
Iteration 3, loss = 0.58548126
Iteration 4, loss = 0.52734360
Iteration 5, loss = 0.47678536
Iteration 6, loss = 0.45313859
Iteration 7, loss = 0.42232346
Iteration 8, loss = 0.39558750
Iteration 9, loss = 0.38044117
Iteration 10, loss = 0.35612025
Iteration 11, loss = 0.35518834
Iteration 12, loss = 0.34159375
Iteration 13, loss = 0.33839568
Iteration 14, loss = 0.32635561
Iteration 15, loss = 0.34611472
Iteration 16, loss = 0.31817204
Iteration 17, loss = 0.30700427
Iteration 18, loss = 0.32742575
Iteration 19, loss = 0.31471476
Iteration 20, loss = 0.30709881
Iteration 21, loss = 0.29166234
Iteration 22, loss = 0.28228180
Iteration 23, loss = 0.27490541
Iteration 24, loss = 0.27533136
Iteration 25, loss = 0.26629915
Iteration 26, loss = 0.26159329
Iteration 27, loss = 0.26032204
Iteration 28, loss = 0.25679464
Iteration 29, loss = 0.25686633
Iteration 30, loss = 0.24719587
Iteration 31, loss = 0.24094161
Iteration 32, los

GridSearchCV(cv=10,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('one_hot_encoder',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         []),
                                                                        ('standard_scaler',
                                                                         StandardScaler(),
                                                                         ['MSSubClass',
                                                                          'LotFrontage',
                                                                          'LotArea',
                                                                          'OverallQual',
                                                                          'OverallCond',
                                                                          'YearBuilt',
                                                                          'YearRemodAdd',
                                                                          'MasVnrArea',
                                                                          'BsmtFinSF1',
                                                                          'BsmtFinSF2',
                                                                          'BsmtUnfSF',
                                                                          'TotalBsmt...
                                                                          'GarageYrBlt',
                                                                          'GarageCars',
                                                                          'GarageArea',
                                                                          'WoodDeckSF',
                                                                          'OpenPorchSF',
                                                                          'EnclosedPorch', ...])])),
                                       ('mlpclassifier',
                                        MLPClassifier(activation='tanh',
                                                      hidden_layer_sizes=(5, 3),
                                                      verbose=True))]),
             n_jobs=2,
             param_grid={'mlpclassifier__hidden_layer_sizes': ((3, 2), (5, 3),
                                                               (10, 2)),
                         'mlpclassifier__learning_rate_init': (0.01, 0.1, 1,
                                                               10),
                         'mlpclassifier__max_iter': (100, 200, 500, 1000)})

In [490]:
ypredMT = model_grid_search.predict(data_train)
cmTM = confusion_matrix(target_train,ypredMT)
accuracyTM = accuracy_score(target_train,ypredMT)
precisionTM = precision_score(target_train, ypredMT,average='micro')
recallTM = recall_score(target_train, ypredMT,average='micro')
f1TM = f1_score(target_train,ypredMT,average='micro')
print('Matriz de confusión\n',cmT)
print('Accuracy: ',accuracyT)
print('Precision: ', precisionT)
print('recall: ',recallT)

Matriz de confusión
 [[198   8  10]
 [  2  57  26]
 [ 14  30  65]]
Accuracy:  0.7804878048780488
Precision:  0.7804878048780488
recall:  0.7804878048780488


In [491]:
ypredMT = model_grid_search.predict(data_test)
cmTM = confusion_matrix(target_test,ypredMT)
accuracyTM = accuracy_score(target_test,ypredMT)
precisionTM = precision_score(target_test, ypredMT,average='micro')
recallTM = recall_score(target_test, ypredMT,average='micro')
f1TM = f1_score(target_test,ypredMT,average='micro')
print('Matriz de confusión\n',cmT)
print('Accuracy: ',accuracyT)
print('Precision: ', precisionT)
print('recall: ',recallT)

Matriz de confusión
 [[198   8  10]
 [  2  57  26]
 [ 14  30  65]]
Accuracy:  0.7804878048780488
Precision:  0.7804878048780488
recall:  0.7804878048780488


In [492]:
data_train, data_test,target_train, target_test = train_test_split(data, toRegresion,test_size=0.3,train_size=0.7)
data_train.columns
data_train = data_train.dropna()
target_train = target_train[data_train.index]  # Asegúrate de alinear los objetivos después de eliminar las filas
data_test = data_test.dropna()
target_test = target_test[data_test.index]  # Asegúrate de alinear los objetivos después de eliminar las filas

In [493]:
mlpT = MLPClassifier(activation="tanh",verbose=True,hidden_layer_sizes=(5,3))
mlpT.fit(data_train,target_train)
y_predT = mlpT.predict(data_test)
X_predT = mlpT.predict(data_train)
y_predT

Iteration 1, loss = 6.19332271
Iteration 2, loss = 6.18836706
Iteration 3, loss = 6.18431020
Iteration 4, loss = 6.18015056
Iteration 5, loss = 6.17605141
Iteration 6, loss = 6.17177234
Iteration 7, loss = 6.16754237
Iteration 8, loss = 6.16297256
Iteration 9, loss = 6.15840835
Iteration 10, loss = 6.15357532
Iteration 11, loss = 6.14869036
Iteration 12, loss = 6.14364577
Iteration 13, loss = 6.13854284
Iteration 14, loss = 6.13331517
Iteration 15, loss = 6.12808245
Iteration 16, loss = 6.12265049
Iteration 17, loss = 6.11717134
Iteration 18, loss = 6.11185678
Iteration 19, loss = 6.10649804
Iteration 20, loss = 6.10119567
Iteration 21, loss = 6.09588962
Iteration 22, loss = 6.09055299
Iteration 23, loss = 6.08551514
Iteration 24, loss = 6.08023354
Iteration 25, loss = 6.07535514
Iteration 26, loss = 6.07054968
Iteration 27, loss = 6.06558433
Iteration 28, loss = 6.06102034
Iteration 29, loss = 6.05662041
Iteration 30, loss = 6.05195389
Iteration 31, loss = 6.04787236
Iteration 32, los

array([110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000,
       110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000,
       110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000,
       110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000,
       110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000,
       110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000,
       110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000,
       110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000,
       110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000,
       110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000,
       110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000,
       110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000,
       110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000,
       110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000,
      

In [494]:
print("-------------------- SVM regresion Model ------------------------------------")
print("Root Mean squared error: %.2f" % root_mean_squared_error(target_test, y_predT))
print("Mean squared error: %.2f" % mean_squared_error(target_test, y_predT))
print('R^2 score: %.2f' % r2_score(target_test, y_predT))


-------------------- SVM regresion Model ------------------------------------
Root Mean squared error: 115250.06
Mean squared error: 13282575892.71
R^2 score: -1.06


In [495]:
print("-------------------- SVM regresion Model ------------------------------------")
print("Root Mean squared error: %.2f" % root_mean_squared_error(target_train, X_predT))
print("Mean squared error: %.2f" % mean_squared_error(target_train, X_predT))
print('R^2 score: %.2f' % r2_score(target_train, X_predT))


-------------------- SVM regresion Model ------------------------------------
Root Mean squared error: 106140.73
Mean squared error: 11265854851.38
R^2 score: -0.85


## Modelo 2 RNA

In [504]:
mlpR = make_pipeline(preprocesador,MLPClassifier(activation="logistic",verbose=True,hidden_layer_sizes=(5,3)))
mlpR

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('one_hot_encoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  []),
                                                 ('standard_scaler',
                                                  StandardScaler(),
                                                  ['MSSubClass', 'LotFrontage',
                                                   'LotArea', 'OverallQual',
                                                   'OverallCond', 'YearBuilt',
                                                   'YearRemodAdd', 'MasVnrArea',
                                                   'BsmtFinSF1', 'BsmtFinSF2',
                                                   'BsmtUnfSF', 'TotalBsmtSF',
                                                   '1stFlrSF', '2ndFlrSF',
                                                   'LowQualFinSF', 'GrLivArea',
                                                   'BsmtFullBath',
                                                   'BsmtHalfBath', 'FullBath',
                                                   'HalfBath', 'BedroomAbvGr',
                                                   'KitchenAbvGr',
                                                   'TotRmsAbvGrd', 'Fireplaces',
                                                   'GarageYrBlt', 'GarageCars',
                                                   'GarageArea', 'WoodDeckSF',
                                                   'OpenPorchSF',
                                                   'EnclosedPorch', ...])])),
                ('mlpclassifier',
                 MLPClassifier(activation='logistic', hidden_layer_sizes=(5, 3),
                               verbose=True))])

In [505]:
mlpR.get_params().keys()

dict_keys(['memory', 'steps', 'verbose', 'columntransformer', 'mlpclassifier', 'columntransformer__n_jobs', 'columntransformer__remainder', 'columntransformer__sparse_threshold', 'columntransformer__transformer_weights', 'columntransformer__transformers', 'columntransformer__verbose', 'columntransformer__verbose_feature_names_out', 'columntransformer__one_hot_encoder', 'columntransformer__standard_scaler', 'columntransformer__one_hot_encoder__categories', 'columntransformer__one_hot_encoder__drop', 'columntransformer__one_hot_encoder__dtype', 'columntransformer__one_hot_encoder__feature_name_combiner', 'columntransformer__one_hot_encoder__handle_unknown', 'columntransformer__one_hot_encoder__max_categories', 'columntransformer__one_hot_encoder__min_frequency', 'columntransformer__one_hot_encoder__sparse_output', 'columntransformer__standard_scaler__copy', 'columntransformer__standard_scaler__with_mean', 'columntransformer__standard_scaler__with_std', 'mlpclassifier__activation', 'mlpcl

In [506]:
data_train, data_test, target_train, target_test = train_test_split(
    data, target, train_size=0.7,test_size=0.3)
print("Shape train",data_train.shape)
print("Shape test",data_test.shape)
data_train = data_train.dropna()
target_train = target_train[data_train.index]  # Asegúrate de alinear los objetivos después de eliminar las filas
data_test = data_test.dropna()
target_test = target_test[data_test.index]  # Asegúrate de alinear los objetivos después de eliminar las filas
data.isnull().sum()

Shape train (1021, 301)
Shape test (438, 301)


MSSubClass               0
LotFrontage              0
LotArea                  0
OverallQual              0
OverallCond              0
                        ..
SaleCondition_Family     0
SaleCondition_AdjLand    0
SaleCondition_Alloca     0
SaleCondition_Abnorml    0
SaleCondition_Partial    0
Length: 301, dtype: int64

In [507]:
mlpR.fit(data_train,target_train)

Iteration 1, loss = 1.17139055
Iteration 2, loss = 1.15945774
Iteration 3, loss = 1.14824842
Iteration 4, loss = 1.13795160
Iteration 5, loss = 1.12848108
Iteration 6, loss = 1.11954441
Iteration 7, loss = 1.11167421
Iteration 8, loss = 1.10407593
Iteration 9, loss = 1.09701705
Iteration 10, loss = 1.09059057
Iteration 11, loss = 1.08438360
Iteration 12, loss = 1.07862487
Iteration 13, loss = 1.07283689
Iteration 14, loss = 1.06740101
Iteration 15, loss = 1.06202466
Iteration 16, loss = 1.05707872
Iteration 17, loss = 1.05172095
Iteration 18, loss = 1.04663967
Iteration 19, loss = 1.04178657
Iteration 20, loss = 1.03661568
Iteration 21, loss = 1.03173558
Iteration 22, loss = 1.02678833
Iteration 23, loss = 1.02214153
Iteration 24, loss = 1.01742606
Iteration 25, loss = 1.01278749
Iteration 26, loss = 1.00841020
Iteration 27, loss = 1.00404249
Iteration 28, loss = 0.99964434
Iteration 29, loss = 0.99556392
Iteration 30, loss = 0.99163301
Iteration 31, loss = 0.98777128
Iteration 32, los


Iteration 68, loss = 0.86740303
Iteration 69, loss = 0.86390143
Iteration 70, loss = 0.86034871
Iteration 71, loss = 0.85681573
Iteration 72, loss = 0.85324027
Iteration 73, loss = 0.84958566
Iteration 74, loss = 0.84599280
Iteration 75, loss = 0.84226787
Iteration 76, loss = 0.83858229
Iteration 77, loss = 0.83484905
Iteration 78, loss = 0.83107922
Iteration 79, loss = 0.82728362
Iteration 80, loss = 0.82347734
Iteration 81, loss = 0.81965757
Iteration 82, loss = 0.81575500
Iteration 83, loss = 0.81184731
Iteration 84, loss = 0.80791703
Iteration 85, loss = 0.80394457
Iteration 86, loss = 0.79997293
Iteration 87, loss = 0.79598270
Iteration 88, loss = 0.79197379
Iteration 89, loss = 0.78791292
Iteration 90, loss = 0.78387672
Iteration 91, loss = 0.77979124
Iteration 92, loss = 0.77574969
Iteration 93, loss = 0.77168251
Iteration 94, loss = 0.76761530
Iteration 95, loss = 0.76352365
Iteration 96, loss = 0.75946960
Iteration 97, loss = 0.75543817
Iteration 98, loss = 0.75136532
Iterati

c:\Users\lijv1\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('one_hot_encoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  []),
                                                 ('standard_scaler',
                                                  StandardScaler(),
                                                  ['MSSubClass', 'LotFrontage',
                                                   'LotArea', 'OverallQual',
                                                   'OverallCond', 'YearBuilt',
                                                   'YearRemodAdd', 'MasVnrArea',
                                                   'BsmtFinSF1', 'BsmtFinSF2',
                                                   'BsmtUnfSF', 'TotalBsmtSF',
                                                   '1stFlrSF', '2ndFlrSF',
                                                   'LowQualFinSF', 'GrLivArea',
                                                   'BsmtFullBath',
                                                   'BsmtHalfBath', 'FullBath',
                                                   'HalfBath', 'BedroomAbvGr',
                                                   'KitchenAbvGr',
                                                   'TotRmsAbvGrd', 'Fireplaces',
                                                   'GarageYrBlt', 'GarageCars',
                                                   'GarageArea', 'WoodDeckSF',
                                                   'OpenPorchSF',
                                                   'EnclosedPorch', ...])])),
                ('mlpclassifier',
                 MLPClassifier(activation='logistic', hidden_layer_sizes=(5, 3),
                               verbose=True))])

In [508]:
ypredM = mlpR.predict(data_train)
cmT = confusion_matrix(target_train,ypredM)
accuracyT = accuracy_score(target_train,ypredM)
precisionT = precision_score(target_train, ypredM,average='micro')
recallT =  recall_score(target_train, ypredM,average='micro')
f1T = f1_score(target_train,ypredM,average='micro')
print('Matriz de confusión\n',cmT)
print('Accuracy: ',accuracyT)
print('Precision: ', precisionT)
print('recall: ',recallT)

Matriz de confusión
 [[496   0   3]
 [  0   0 212]
 [ 13   0 229]]
Accuracy:  0.7607555089192025
Precision:  0.7607555089192025
recall:  0.7607555089192025


In [509]:
ypredM = mlpR.predict(data_test)
cmT = confusion_matrix(target_test,ypredM)
accuracyT = accuracy_score(target_test,ypredM)
precisionT = precision_score(target_test, ypredM,average='micro')
recallT =  recall_score(target_test, ypredM,average='micro')
f1T = f1_score(target_test,ypredM,average='micro')
print('Matriz de confusión\n',cmT)
print('Accuracy: ',accuracyT)
print('Precision: ', precisionT)
print('recall: ',recallT)

Matriz de confusión
 [[198   0  19]
 [  0   0  87]
 [ 21   1  91]]
Accuracy:  0.6930455635491607
Precision:  0.6930455635491607
recall:  0.6930455635491607


## Tuneo de Parametros

In [510]:
parametros_tun  = param_grid = {
    'mlpclassifier__max_iter': (100,200,500,1000),
    'mlpclassifier__learning_rate_init': (0.01, 0.1, 1,10),
    'mlpclassifier__hidden_layer_sizes':((3,2),(5,3),(10,2))}
model_grid_search = GridSearchCV(mlpR, param_grid=parametros_tun,
                                 n_jobs=2, cv=10) #Vamos a usar dos procesadores(n_jobs), y 10 k-folds
model_grid_search.fit(data_train, target_train)

Iteration 1, loss = 1.08900820
Iteration 2, loss = 0.84653940
Iteration 3, loss = 0.72607704
Iteration 4, loss = 0.59409418
Iteration 5, loss = 0.50366171
Iteration 6, loss = 0.48238265
Iteration 7, loss = 0.46632207
Iteration 8, loss = 0.45452642
Iteration 9, loss = 0.43879920
Iteration 10, loss = 0.42918455
Iteration 11, loss = 0.42005993
Iteration 12, loss = 0.41053133
Iteration 13, loss = 0.39648259
Iteration 14, loss = 0.38341383
Iteration 15, loss = 0.36460140
Iteration 16, loss = 0.34314516
Iteration 17, loss = 0.32181389
Iteration 18, loss = 0.30282576
Iteration 19, loss = 0.28213892
Iteration 20, loss = 0.26674239
Iteration 21, loss = 0.24952724
Iteration 22, loss = 0.23205681
Iteration 23, loss = 0.22019768
Iteration 24, loss = 0.19920872
Iteration 25, loss = 0.18271721
Iteration 26, loss = 0.17662203
Iteration 27, loss = 0.17420507
Iteration 28, loss = 0.16605783
Iteration 29, loss = 0.15817613
Iteration 30, loss = 0.15017724
Iteration 31, loss = 0.14387734
Iteration 32, los

GridSearchCV(cv=10,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('one_hot_encoder',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         []),
                                                                        ('standard_scaler',
                                                                         StandardScaler(),
                                                                         ['MSSubClass',
                                                                          'LotFrontage',
                                                                          'LotArea',
                                                                          'OverallQual',
                                                                          'OverallCond',
                                                                          'YearBuilt',
                                                                          'YearRemodAdd',
                                                                          'MasVnrArea',
                                                                          'BsmtFinSF1',
                                                                          'BsmtFinSF2',
                                                                          'BsmtUnfSF',
                                                                          'TotalBsmt...
                                                                          'GarageYrBlt',
                                                                          'GarageCars',
                                                                          'GarageArea',
                                                                          'WoodDeckSF',
                                                                          'OpenPorchSF',
                                                                          'EnclosedPorch', ...])])),
                                       ('mlpclassifier',
                                        MLPClassifier(activation='logistic',
                                                      hidden_layer_sizes=(5, 3),
                                                      verbose=True))]),
             n_jobs=2,
             param_grid={'mlpclassifier__hidden_layer_sizes': ((3, 2), (5, 3),
                                                               (10, 2)),
                         'mlpclassifier__learning_rate_init': (0.01, 0.1, 1,
                                                               10),
                         'mlpclassifier__max_iter': (100, 200, 500, 1000)})

In [511]:
ypredMT = model_grid_search.predict(data_train)
cmTM = confusion_matrix(target_train,ypredMT)
accuracyTM = accuracy_score(target_train,ypredMT)
precisionTM = precision_score(target_train, ypredMT,average='micro')
recallTM = recall_score(target_train, ypredMT,average='micro')
f1TM = f1_score(target_train,ypredMT,average='micro')
print('Matriz de confusión\n',cmT)
print('Accuracy: ',accuracyT)
print('Precision: ', precisionT)
print('recall: ',recallT)

Matriz de confusión
 [[198   0  19]
 [  0   0  87]
 [ 21   1  91]]
Accuracy:  0.6930455635491607
Precision:  0.6930455635491607
recall:  0.6930455635491607


In [512]:
ypredMT = model_grid_search.predict(data_test)
cmTM = confusion_matrix(target_test,ypredMT)
accuracyTM = accuracy_score(target_test,ypredMT)
precisionTM = precision_score(target_test, ypredMT,average='micro')
recallTM = recall_score(target_test, ypredMT,average='micro')
f1TM = f1_score(target_test,ypredMT,average='micro')
print('Matriz de confusión\n',cmT)
print('Accuracy: ',accuracyT)
print('Precision: ', precisionT)
print('recall: ',recallT)

Matriz de confusión
 [[198   0  19]
 [  0   0  87]
 [ 21   1  91]]
Accuracy:  0.6930455635491607
Precision:  0.6930455635491607
recall:  0.6930455635491607


In [513]:
data_train, data_test,target_train, target_test = train_test_split(data, toRegresion,test_size=0.3,train_size=0.7)
data_train.columns
data_train = data_train.dropna()
target_train = target_train[data_train.index]  # Asegúrate de alinear los objetivos después de eliminar las filas
data_test = data_test.dropna()
target_test = target_test[data_test.index]  # Asegúrate de alinear los objetivos después de eliminar las filas

In [514]:
mlpR = MLPClassifier(activation="logistic",verbose=True,hidden_layer_sizes=(5,3))
mlpR.fit(data_train,target_train)
y_predR = mlpR.predict(data_test)
X_predR = mlpR.predict(data_train)
y_predR

Iteration 1, loss = 6.20190668
Iteration 2, loss = 6.19666925
Iteration 3, loss = 6.19239546
Iteration 4, loss = 6.18822334
Iteration 5, loss = 6.18379879
Iteration 6, loss = 6.17974614
Iteration 7, loss = 6.17531120
Iteration 8, loss = 6.17111920
Iteration 9, loss = 6.16692968
Iteration 10, loss = 6.16262126
Iteration 11, loss = 6.15838133
Iteration 12, loss = 6.15397294
Iteration 13, loss = 6.14964986
Iteration 14, loss = 6.14553161
Iteration 15, loss = 6.14120276
Iteration 16, loss = 6.13687191
Iteration 17, loss = 6.13271693
Iteration 18, loss = 6.12839732
Iteration 19, loss = 6.12406442
Iteration 20, loss = 6.11971742
Iteration 21, loss = 6.11538753
Iteration 22, loss = 6.11120691
Iteration 23, loss = 6.10692367
Iteration 24, loss = 6.10267383
Iteration 25, loss = 6.09853311
Iteration 26, loss = 6.09436435
Iteration 27, loss = 6.09036970
Iteration 28, loss = 6.08647502
Iteration 29, loss = 6.08225465
Iteration 30, loss = 6.07821179
Iteration 31, loss = 6.07419999
Iteration 32, los

array([140000, 140000, 140000, 140000, 140000, 140000, 140000, 140000,
       140000, 140000, 140000, 140000, 140000, 140000, 140000, 140000,
       140000, 140000, 140000, 140000, 140000, 140000, 140000, 140000,
       140000, 140000, 140000, 140000, 140000, 140000, 140000, 140000,
       140000, 140000, 140000, 140000, 140000, 140000, 140000, 140000,
       140000, 140000, 140000, 140000, 140000, 140000, 140000, 140000,
       140000, 140000, 140000, 140000, 140000, 140000, 140000, 140000,
       140000, 140000, 140000, 140000, 140000, 140000, 140000, 140000,
       140000, 140000, 140000, 140000, 140000, 140000, 140000, 140000,
       140000, 140000, 140000, 140000, 140000, 140000, 140000, 140000,
       140000, 140000, 140000, 140000, 140000, 140000, 140000, 140000,
       140000, 140000, 140000, 140000, 140000, 140000, 140000, 140000,
       140000, 140000, 140000, 140000, 140000, 140000, 140000, 140000,
       140000, 140000, 140000, 140000, 140000, 140000, 140000, 140000,
      

In [515]:
print("-------------------- SVM regresion Model ------------------------------------")
print("Root Mean squared error: %.2f" % root_mean_squared_error(target_test, y_predR))
print("Mean squared error: %.2f" % mean_squared_error(target_test, y_predR))
print('R^2 score: %.2f' % r2_score(target_test, y_predR))


-------------------- SVM regresion Model ------------------------------------
Root Mean squared error: 97739.47
Mean squared error: 9553004106.50
R^2 score: -0.32


In [516]:
print("-------------------- SVM regresion Model ------------------------------------")
print("Root Mean squared error: %.2f" % root_mean_squared_error(target_train, X_predR))
print("Mean squared error: %.2f" % mean_squared_error(target_train, X_predR))
print('R^2 score: %.2f' % r2_score(target_train, X_predR))


-------------------- SVM regresion Model ------------------------------------
Root Mean squared error: 87858.42
Mean squared error: 7719101596.70
R^2 score: -0.33


In [518]:
print("-------------------- SVM regresion Model ------------------------------------")
print("Root Mean squared error: %.2f" % root_mean_squared_error(target_test, y_predR))
print("Mean squared error: %.2f" % mean_squared_error(target_test, y_predR))
print('R^2 score: %.2f' % r2_score(target_test, y_predR))


-------------------- SVM regresion Model ------------------------------------
Root Mean squared error: 97739.47
Mean squared error: 9553004106.50
R^2 score: -0.32


In [519]:
print("-------------------- SVM regresion Model ------------------------------------")
print("Root Mean squared error: %.2f" % root_mean_squared_error(target_train, X_predR))
print("Mean squared error: %.2f" % mean_squared_error(target_train, X_predR))
print('R^2 score: %.2f' % r2_score(target_train, X_predR))


-------------------- SVM regresion Model ------------------------------------
Root Mean squared error: 87858.42
Mean squared error: 7719101596.70
R^2 score: -0.33
